# Generated by Django 3.1.7 on 2021-09-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210819_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='address',
            field=models.CharField(default='NoString', max_length=250),
        ),
        migrations.AlterField(
            model_name='space',
            name='coordinates',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='SpaceRoommates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('contactnumber', models.CharField(max_length=13)),
                ('space', models.ForeignKey(db_column='space', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.space')),
            ],
            options={
                'db_table': 'Roommates',
            },
        ),
    ]
