# Generated by Django 3.1.7 on 2021-09-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210930_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='coordinates',
            field=models.CharField(max_length=100),
        ),
    ]
