# Generated by Django 3.1.7 on 2021-09-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20210930_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='coordinates',
            field=models.CharField(max_length=200),
        ),
    ]
